name: Test and Run Training Script

on:
  push:
    branches: [ main ]

jobs:
  test-and-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # This step installs everything from requirements.txt, including mlflow
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pytest test/

      - name: Run Training Script
        run: python src/train.py
